apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets-db
  labels:
    app: backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: backend-secrets-db
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    # Database connection secrets from nizami/prod/db
    - secretKey: DB_HOST
      remoteRef:
        key: nizami/prod/db
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: nizami/prod/db
        property: DB_PORT
    - secretKey: DB_DATABASE
      remoteRef:
        key: nizami/prod/db
        property: DB_DATABASE
    - secretKey: DB_USERNAME
      remoteRef:
        key: nizami/prod/db
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: nizami/prod/db
        property: DB_PASSWORD

