apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets-functional
  namespace: nizami-stage
  labels:
    app: backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    namespace: nizami-stage
    kind: SecretStore
  target:
    name: backend-secrets-functional
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    # Functional/application secrets from nizami/prod/functional
    - secretKey: SECRET_KEY
      remoteRef:
        key: nizami/prod/functional
        property: SECRET_KEY
    - secretKey: DJANGO_SETTINGS_MODULE
      remoteRef:
        key: nizami/prod/functional
        property: DJANGO_SETTINGS_MODULE
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: nizami/prod/functional
        property: OPENAI_API_KEY
    - secretKey: MOYASAR_URL
      remoteRef:
        key: nizami/prod/functional
        property: MOYASAR_URL
    - secretKey: MOYASAR_SECRET_KEY
      remoteRef:
        key: nizami/prod/functional
        property: MOYASAR_SECRET_KEY
    - secretKey: MOYASAR_WEBHOOK_SECRET_KEY
      remoteRef:
        key: nizami/prod/functional
        property: MOYASAR_WEBHOOK_SECRET_KEY
    - secretKey: EMAIL_HOST
      remoteRef:
        key: nizami/prod/functional
        property: EMAIL_HOST
    - secretKey: EMAIL_PORT
      remoteRef:
        key: nizami/prod/functional
        property: EMAIL_PORT
    - secretKey: EMAIL_HOST_USER
      remoteRef:
        key: nizami/prod/functional
        property: EMAIL_HOST_USER
    - secretKey: EMAIL_HOST_PASSWORD
      remoteRef:
        key: nizami/prod/functional
        property: EMAIL_HOST_PASSWORD
    - secretKey: EMAIL_FROM_ADDRESS
      remoteRef:
        key: nizami/prod/functional
        property: EMAIL_FROM_ADDRESS
    - secretKey: FRONTEND_DOMAIN
      remoteRef:
        key: nizami/prod/functional
        property: FRONTEND_DOMAIN
    - secretKey: FRONTEND_RESET_PASSWORD_TEMPLATE
      remoteRef:
        key: nizami/prod/functional
        property: FRONTEND_RESET_PASSWORD_TEMPLATE
    - secretKey: ASPOSE_LICENSE_PATH
      remoteRef:
        key: nizami/prod/functional
        property: ASPOSE_LICENSE_PATH
    - secretKey: DEBUG
      remoteRef:
        key: nizami/prod/functional
        property: DEBUG

