apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nizami-stage

resources:
  - ../base
  - externalsecret-db.yaml
  - externalsecret-functional.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nizami-stage
      spec:
        replicas: 1
    target:
      kind: Deployment
      name: backend
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: nizami-stage
    target:
      kind: Service
      name: backend